# Generated by Django 5.0.4 on 2024-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='name',
            field=models.CharField(default='Not named', max_length=200),
        ),
        migrations.AddField(
            model_name='rectangle',
            name='color',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
