# Generated by Django 5.0.4 on 2024-05-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_remove_drawing_author_drawing_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='drawing',
            name='width',
            field=models.IntegerField(default=100),
        ),
    ]
