# Generated by Django 5.0.4 on 2024-05-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_drawing_height_drawing_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='drawing',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='drawing',
            name='tags',
            field=models.ManyToManyField(to='pictures.tag'),
        ),
    ]
